version: "2"
services:
  webserver:
    environment:
      MOODLE_DOCKER_DBTYPE: mysqli
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
  db:
    image: mysql:${MOODLE_DOCKER_DB_VERSION:-8.0}
    command: >
                --character-set-server=utf8mb4
                --collation-server=utf8mb4_bin
                --skip-log-bin
    environment:
      MYSQL_ROOT_PASSWORD: "moodlepass"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "moodlepass"
      MYSQL_DATABASE: moodle
    volumes:
      - /var/dockerdb.mysql:/var/lib/mysql
